#pragma once
#include <fstream>
#include <vector>
#include <string>
#include <map>
#include <algorithm>
#include <fstream>
#include <stdlib.h>
#include <string.h>
#include <iostream>
#include <cstring>
#include <stdio.h>
#include <sstream>

using std::cin;
using std::cout;
using std::endl;
using std::string;
using std::vector;
using std::map;
using std::fstream;
using std::istringstream;
